### ISSUE TITLE
Publish HTML Pluign with EcmaScript proposal decorators yields Exceptions

### ISSUE THREAD

**Issue by shfx** [esdoc/esdoc-plugins#32]
I have some issues with eslint-publish-html combined with esdoc-ecmascript-proposal-plugin and decorators feature.

When I combine those two i get this in the terminal:

```
Error: DocBuilder: can not resolve file name.
    at ClassDocBuilder._getOutputFileName (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:613:15)
    at ClassDocBuilder._getURL (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:573:29)
    at ClassDocBuilder._buildDocLinkHTML (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:784:24)
    at ClassDocBuilder._buildTypeDocLinkHTML (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:748:23)
    at ClassDocBuilder._buildSignatureHTML (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:835:27)
    at ice.loop (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:335:34)
    at IceCap.loop (/SomePath/ice-cap/out/src/IceCap.js:261:9)
    at ClassDocBuilder._buildSummaryDoc (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:331:9)
    at ClassDocBuilder._buildSummaryHTML (/SomePath/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:307:27)
    at ClassDocBuilder._buildClassDoc (/SomePath/esdoc-publish-html-plugin/out/src/Builder/ClassDocBuilder.js:115:36)
```

`_getOutputFileName` laks of handling case where `doc.kind=="index"`.

Any ideas why those two won't click?

**Comment by shfx** [comment]
I tracked the problem. It's not related to `esdoc-ecmascript-proposal-plugin` tho. `"decorators": false` option blocked a file from being parsed and after turning it on, `eslint-publish-html` parsed types and tried to find a file based some kind of assumption.

When you have a old codebase and somebody annotated some unknown type in `@param` comment like this:

```
@param {???} param
``` 

`eslint-publish-html` have a case that tries to resolve an optional type `?number` and tried to find a file or generate an url using filename "?" which somehow ended up being resolved to file of kind: `index`.

Can't reproduce it now on a smaller codebase 😢
