### ISSUE TITLE
Unable to import @typedef

### ISSUE THREAD

**Issue by xlozano-newrelic** [esdoc/esdoc-plugins#93]
I have a file `utils.js` with:

```
/**
 * @typedef Location
 *
 * @property {string} pathname
 * @property {string} search
 * @property {string} hash
 */
```

On another file, I'm trying to do:

```
/**
 * @typedef {import('../../../../../utils').Location} Location
 */
``` 

But I'm getting this error:

```
[docs:build] SyntaxError: Invalid regular expression: /[~]import('../../../../.$/: Unterminated group
    at new RegExp (<anonymous>)
    at IdentifiersDocBuilder._findByName (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:117:20)
    at IdentifiersDocBuilder._findByName (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:132:30)
    at IdentifiersDocBuilder._findByName (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:132:30)
    at IdentifiersDocBuilder._buildDocLinkHTML (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:785:22)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:767:19)
    at IdentifiersDocBuilder._buildSignatureHTML (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:871:34)
    at /test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:338:34
    at IceCap.loop (/test/node_modules/ice-cap/out/src/IceCap.js:261:9)
    at IdentifiersDocBuilder._buildSummaryDoc (/test/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:334:9)
```

I understand that the error is related to the relative path, is there any workaround to this?

**Comment by hudsonansley** [comment]
We're running into the same issue. I see this was posted quite a while ago with no response so far. Any possibility this can get some attention?
